### PR TITLE
Publish events for successful and failed replica creation

### LINKED ISSUE #348: chore: Send a K8s event in the case where enough replicas can't be created on a multi-zone AKS cluster
**What happened**:
In case where an AKS cluster is spread out across multiple zones, and the zone where LRS disk is created doesn't have enough nodes to create replicas on, the number of replicas created will be the minimum of replicas requested by the Customer and the number of nodes in the zone.

The customer should be informed of this by having a Kubernetes event that mentions that requested number of replicas couldn't be created.

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by nearora-msft**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #348 

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

File: pkg/controller/common.go [hunk 1]
```diff
@@ -597,7 +589,7 @@ func (c *SharedState) isVolumeVisited(azVolumeName string) bool {
 	return visited
 }
 
-func getRankedNodesForReplicaAttachments(ctx context.Context, azr azReconciler, volumes, pods []string) ([]string, error) {
+func getRankedNodesForReplicaAttachments(ctx context.Context, azr azReconciler, volumes []string, podsObjs ...v1.Pod) ([]string, error) {
```
Comment (edreed) [inline pkg/controller/common.go:592]: Why take Pods as a variable number of arguments vs. a slice (i.e. `pods []v1.Pod`)?

File: pkg/controller/common.go [hunk 2]
```diff
@@ -1529,29 +1527,44 @@ func (c *SharedState) createReplicas(ctx context.Context, remainingReplicas int,
...
 	return nil
 }
 
-func (c *SharedState) getNodesForReplica(ctx context.Context, volumeName string, pods []string, numReplica int, azr azReconciler) ([]string, error) {
+func (c *SharedState) getNodesForReplica(ctx context.Context, volumeName string, podObjs []v1.Pod, numReplica int, azr azReconciler) ([]string, error) {
 	var err error
-	if pods == nil {
-		pods, err = c.getPodsFromVolume(volumeName)
+	if len(podObjs) == 0 {
+		pods, err := c.getPodsFromVolume(volumeName)
```
Comment (edreed) [inline pkg/controller/common.go:1548]: Perhaps `getPodsFromVolume` should return `[]v1.Pod` instead of just pod names since in both usages we're now getting the `v1.Pod` anyway?

File: pkg/controller/common.go [hunk 3]
```diff
@@ -447,18 +451,6 @@ func (c *SharedState) getPodsFromVolume(volumeName string) ([]string, error) {
...
-		podVolumes, err := c.getVolumesFromPod(pod)
-		if err != nil {
-			return nil, err
-		}
-		volumes = append(volumes, podVolumes...)
-	}
-	return volumes, nil
-}
-
 func (c *SharedState) getVolumesForPodObjs(pods ...v1.Pod) ([]string, error) {
```
Comment (edreed) [inline pkg/controller/common.go:454]: `getVolumesForPodObjs` should really take `[]v1.Pod` rather than variadic arguments.

File: pkg/controller/common.go [hunk 4]
```diff
@@ -1529,29 +1527,44 @@ func (c *SharedState) createReplicas(ctx context.Context, remainingReplicas int,
 		remainingReplicas--
 	}
 
+	for _, podObj := range podObjs {
+		azr.getSharedState().eventRecorder.Eventf(podObj.DeepCopyObject(), v1.EventTypeNormal, ReplicaAttachmentCreationSuccessEvent, "%d replica attachment(s) created for volume %s", requiredReplicas-remainingReplicas, volumeName)
```
Comment (edreed) [inline pkg/controller/common.go:1531]: The replica `AzVolumeAttachment` instance has been created at this point, but the disk attach operation has not yet completed. We should generate a node event when the attachment has completed, e.g. "Replica mount of volume %s successfully attached to node %s" on success and "Replica mount of volume %s failed to attach on node %s with error %q" on error.

File: pkg/controller/common.go [hunk 5]
```diff
@@ -1529,29 +1527,44 @@ func (c *SharedState) createReplicas(ctx context.Context, remainingReplicas int,
...
+	}
+
 	if remainingReplicas > 0 {
 		//no failed replica attachments, but there are still more replicas to reach MaxShares
 		request := ReplicaRequest{VolumeName: volumeName, Priority: remainingReplicas}
 		c.priorityReplicaRequestsQueue.Push(&request)
+		for _, podObj := range podObjs {
+			azr.getSharedState().eventRecorder.Eventf(podObj.DeepCopyObject(), v1.EventTypeWarning, ReplicaAttachmentCreationFailedEvent, "%d/%d replica attachment(s) for volume %s could not be created. Not enough suitable nodes", remainingReplicas, requiredReplicas, volumeName)
```
Comment (edreed) [inline pkg/controller/common.go:1539]: Consider "There are not enough suitable nodes for %d of the %d requested replica mounts for volume %s."

File: pkg/controller/replica_test.go [hunk 6]
```diff
@@ -386,7 +386,7 @@ func TestGetNodesForReplica(t *testing.T) {
 			mockCtl := gomock.NewController(t)
 			defer mockCtl.Finish()
 			controller := tt.setupFunc(t, mockCtl)
-			nodes, err := getRankedNodesForReplicaAttachments(context.TODO(), controller, tt.volumes, tt.pods)
+			nodes, err := getRankedNodesForReplicaAttachments(context.TODO(), controller, tt.volumes, testPod0)
```
Comment (edreed) [inline pkg/controller/replica_test.go:389]: You should change the `pod` field to `[]v1.Pod` instead of hardcoding the parameter to `testPod0`

File: pkg/controller/common.go (hunk 4 above)
Comment (sunpa93) [reply pkg/controller/common.go:1531]: Should we also generate a PV event for that or would that be unnecessary?

Comment (edreed) [reply pkg/controller/common.go:1531]: I don't believe the PV would be the right target and it doesn't need to be done in both places. The pod is the one requesting the PV be mounted to the primary and replicas. I expected a customer would look at the pod events to determine whether the expected number of replicas had been created and attached.

Comment (edreed) [reply pkg/controller/common.go:1531]: (Removed "node" from my original comment)

File: pkg/controller/common.go (hunk 2 above)
Comment (nearora-msft) [reply pkg/controller/common.go]: Done

File: pkg/controller/common.go (hunk 1 above)
Comment (nearora-msft) [reply pkg/controller/common.go]: Changed

File: pkg/controller/common.go (hunk 3 above)
Comment (nearora-msft) [reply pkg/controller/common.go]: Changed to []v1.Pod

File: pkg/controller/common.go (hunk 5 above)
Comment (nearora-msft) [reply pkg/controller/common.go]: Updated the event message.

File: pkg/controller/common.go (hunk 4 above)
Comment (nearora-msft) [reply pkg/controller/common.go]: Publishing the success & failure events from attach-detach controller now.

File: pkg/controller/attach_detach.go [hunk 7]
```diff
@@ -191,11 +192,22 @@ func (r *ReconcileAttachDetach) triggerAttach(ctx context.Context, azVolumeAttac
...
+		}
+
 		// update AzVolumeAttachment CRI with the result of the attach operation
 		var updateFunc func(interface{}) error
 		if attachErr != nil {
 			klog.Errorf("failed to attach volume %s to node %s: %v", azVolumeAttachment.Spec.VolumeName, azVolumeAttachment.Spec.NodeName, attachErr)
 
+			if len(pods) > 0 {
+				for _, pod := range pods {
+					r.controllerSharedState.eventRecorder.Eventf(pod.DeepCopyObject(), v1.EventTypeWarning, consts.ReplicaAttachmentFailedEvent, "%s mount for volume %s could not attached to node %s", azVolumeAttachment.Spec.RequestedRole, azVolumeAttachment.Spec.VolumeName, azVolumeAttachment.Spec.NodeName)
```
Comment (edreed) [inline pkg/controller/attach_detach.go:207]: It would be useful to include the errors message in the event as well.

**Review by edreed — APPROVED** [review]
I recommend adding error message to attach failure event, but otherwise LGTM.

File: pkg/controller/attach_detach.go (hunk 7 above)
Comment (nearora-msft) [reply pkg/controller/attach_detach.go:207]: I'm not sure if it would be helpful for the customer to understand the error message. I think the error message would be helpful for someone who's debugging the failure but in that case the message is being written in the logs anyway.

One scenario when the customer can do something about the error would be to increase the number of nodes in case there aren't enough suitable nodes and we have a separate error message for that. 

Do you think there can be other scenarios where the customer can take action based on the error message?

Comment (edreed) [reply pkg/controller/attach_detach.go:207]: While I agree that the customer may not be able to take action on the error message, it's likely that event will be part of any CRI raised by the customer in relation to the error. If the error message is in the event, it would help to jump start any investigation on our part /wo having to ask the customer to produce the relevant logs.

Comment (sunpa93) [inline pkg/controller/attach_detach.go:207]: Do we want to raise `ReplicaAttachmentFailedEvent` only for the replica attachments or for all attachments? If latter, Should we change `ReplicaAttachmentFailedEvent` to `AttachmentFailedEvent`?

File: pkg/controller/attach_detach.go [hunk 8]
```diff
@@ -205,6 +217,13 @@ func (r *ReconcileAttachDetach) triggerAttach(ctx context.Context, azVolumeAttac
 		} else {
 			klog.Infof("successfully attached volume (%s) to node (%s) and update status of AzVolumeAttachment (%s)", azVolumeAttachment.Spec.VolumeName, azVolumeAttachment.Spec.NodeName, azVolumeAttachment.Name)
 
+			// Publish event to indicate attachment success
+			if len(pods) > 0 {
+				for _, pod := range pods {
+					r.controllerSharedState.eventRecorder.Eventf(pod.DeepCopyObject(), v1.EventTypeNormal, consts.ReplicaAttachmentSuccessEvent, "%s mount for volume %s successfully attached to node %s", azVolumeAttachment.Spec.RequestedRole, azVolumeAttachment.Spec.VolumeName, azVolumeAttachment.Spec.NodeName)
```
Comment (sunpa93) [inline pkg/controller/attach_detach.go:223]: Same as above comment.

**Review by sunpa93 — APPROVED** [review]
Other than the left comments on event name, LGTM

File: pkg/controller/attach_detach.go (hunk 7 above)
Comment (nearora-msft) [reply pkg/controller/attach_detach.go:207]: Yeah, I think it makes sense to raise these events only for replica attachments as there are other K8s events indicating success/failure for primary attachments. Will add a condition for that.
