### PR TITLE
fix: Use StandardSSD_LRS sku in live resize test.

### LINKED ISSUE #325: test: Add E2E Test to Validate Dynamic Resize [ETA 02/25/2022]
There is already an end-to-end test validating volume expansion, but it scales the StatefulSet to zero before expanding the volume. With the recently added ability to dynamically resize a disk while it is still attached to a VM, we should enhance this test to enabling testing both scenarios. The dynamic resize feature is currently in limited regions, so this test case will need to depend on being deployed to a supported region. Since the V1 driver added support for dynamic resize, the changes should be made upstream, and we'll merge with V2 afterward.

### LINKED ISSUE #399: flake: Live resize test fails in northeurope
**What happened**:

The live resize test is failing when run in North Europe even though the feature is enabled on our subscription and is supposed to be supported in that region. Need to investigate further.

```log
Feb 24 06:57:17.186: INFO: At 2022-02-24 06:46:48 +0000 UTC - event for test-volume-1-azuredisk-volume-tester-mfblf-0: {external-resizer disk.csi.azure.com } VolumeResizeFailed: resize volume "pvc-40f2d937-eb82-45a1-bb2e-83ea4effab09" by resizer "disk.csi.azure.com" failed: rpc error: code = Internal desc = rpc error: code = Internal desc = failed to resize disk(/subscriptions/***/resourceGroups/k8s-e2etest-e8ed16a0-9535-11ec-90f3-3f09839f38f8-rg/providers/Microsoft.Compute/disks/pvc-40f2d937-eb82-45a1-bb2e-83ea4effab09) with error(Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: Code="LiveResizeFailed" Message="Error resizing disk pvc-40f2d937-eb82-45a1-bb2e-83ea4effab09 while it is attached to running VM(s) /subscriptions/***/resourceGroups/k8s-e2eTest-e8ed16a0-9535-11ec-90f3-3f09839f38f8-rg/providers/Microsoft.Compute/virtualMachines/k8s-agentpool1-39769881-2.")
```

**What you expected to happen**:

Live resize test passes in supported regions.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by edreed**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Although not excluded in the document for [Live Resize](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/expand-disks#resize-without-downtime-preview), Standard_LRS disks cannot be resized (at least in northeurope) without first being removed from the VM. This PR re-enables the test and changes the disk SKU to StandardSSD_LRS which can be resized while still attached to a running VM.

**Which issue(s) this PR fixes**:

Fixes #399
Fixes #325 

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

File: test/e2e/dynamic_provisioning_test.go [hunk 1]
```diff
@@ -830,46 +830,44 @@ func (t *dynamicProvisioningTestSuite) defineTests(isMultiZone bool, schedulerNa
...
-			}
-			test.Run(cs, ns, schedulerName)
-		})
-	*/
+		test := testsuites.DynamicallyProvisionedResizeVolumeTest{
+			CSIDriver:              testDriver,
+			Volume:                 volume,
+			Pod:                    pod,
+			ResizeOffline:          false,
+			StorageClassParameters: map[string]string{"skuName": "StandardSSD_LRS"},
```
Comment (kassarl) [inline test/e2e/dynamic_provisioning_test.go:867]: Just for clarification, how was it determined that Standard_LRS was not supported in Northern Europe? I'm fairly certain that my test was on a northeurope cluster as well.

**Review by kassarl — APPROVED** [review]

File: test/e2e/dynamic_provisioning_test.go (hunk 1 above)
Comment (edreed) [reply test/e2e/dynamic_provisioning_test.go:867]: Empirically. The test was failing with the error in #399 when Akash merged from upstream, so we disabled it to investigate. I created a cluster in North Europe, ran the test and observed the same error. After confirming that our subscription did indeed have the LiveResize feature enable, I switched to StandardSSD_LRS and the test passed. It's possible there may have been some recent regression for LiveResize on Standard_LRS.
