### PR TITLE
test: replica test cases fix

### LINKED ISSUE #283: bug: "Should not create replicas on node with non-tolerable taint" fails randomly
**What happened**:

The e2e test case "Should not create replicas on node with non-tolerable taint" fails randomly with the following error:

```
rpc error: code = Internal desc = AzVolumeAttachment (pvc-ef917682-bb89-45f5-925f-207531922061-k8s-agentpool1-27221923-0-attachment) created on a wrong node (k8s-agentpool1-27221923-0)
```

**What you expected to happen**:

It should pass consistently.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by sunpa93**
**What type of PR is this?**
* master nodes don't hold the necessary azuredisk topology label that is required to satisfy azuredisk volumes' required node affinity.
* Hence, this label needs to be added to fully utilize the 3 nodes for replica test cases.
* There were cases observed where the tests were querying for wrong `AzVolumeAttachments` for the wrong volume, resulting in inconsistent test results.
* Hence, the change involves getting PVC name from the pod spec and querying for PV name directly from the PVC object.

/kind test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #283 

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

File: test/e2e/testsuites/dynamically_provisioned_pod_affinity.go [hunk 1]
```diff
@@ -67,6 +67,15 @@ func (t *PodNodeAffinity) Run(client clientset.Interface, namespace *v1.Namespac
 		labelCleanup, err := SetNodeLabels(client, nodeObj, testLabel)
 		framework.ExpectNoError(err)
 		defer labelCleanup()
+
+		// if the node is a master node, it will not have the required node affinity to schedule pod.
+		// so add the label
+		if nodeObj.Labels != nil && nodeObj.Labels[nodeRoleLabel] == "master" {
+			roleLabelCleanup, err := SetNodeLabels(client, nodeObj, map[string]string{driver.TopologyKey: ""})
```
Comment (edreed) [inline test/e2e/testsuites/dynamically_provisioned_pod_affinity.go:74]: So it the label `topology.disk.csi.azure.com/zone` is not set if there is only one master node regardless of whether its multi-az or not. Setting to to "" is the correct value for the single-az case, but in multi-az it should be set to something like "westus2-0". The correct value could be derived from the `topology.kubernetes.io/region` and `topology.kubernetes.io/zone` values which seem to be set regardless.

**Comment by edreed** [comment]
FYI- I had @landreasyan disable the test so that we can make progress before the fix is checked in. You'll need to undo #284 as part of this PR.

**Comment by sunpa93** [comment]
> FYI- I had @landreasyan disable the test so that we can make progress before the fix is checked in. You'll need to undo #284 as part of this PR.

Sounds good

File: test/e2e/testsuites/testsuites.go [hunk 2]
```diff
@@ -1046,6 +1071,61 @@ func SetNodeTaints(c clientset.Interface, node *v1.Node, taints ...v1.Taint) (cl
...
+		csiNode, err := c.StorageV1().CSINodes().Get(context.Background(), nodeName, metav1.GetOptions{})
+		framework.ExpectNoError(err)
+		csiNode.Spec = originalSpec
+		_, _ = c.StorageV1().CSINodes().Update(context.Background(), csiNode, metav1.UpdateOptions{})
+	}
+
+	if csiNode.Spec.Drivers == nil || len(csiNode.Spec.Drivers) == 0 {
+		csiNode.Spec.Drivers = []storagev1.CSINodeDriver{
+			{
+				Name:         "secrets-store.csi.k8s.io",
```
Comment (edreed) [inline test/e2e/testsuites/testsuites.go:1115]: Why do we need to add this driver to the node spec?

**Review by edreed — APPROVED** [review]
Just a question for clarification, but otherwise LGTM.

File: test/e2e/testsuites/testsuites.go (hunk 2 above)
Comment (sunpa93) [reply test/e2e/testsuites/testsuites.go:1115]: This was required to schedule a pod onto master node, otherwise, external-provisioner complains that `no topology key was found in the csi node`. 

https://github.com/kubernetes-csi/external-provisioner/blob/7ae61466a611061ba70da2679358c8bfc8546b6f/pkg/controller/topology.go#L114-L134

**Comment by sunpa93** [comment]
I will merge this PR as the pod affinity PR has some dependencies on the changes. I will revert the merge if necessary.
