### PR TITLE
fix: Do not retry AttachDisk (or any operation) on non-retriable errors.

### LINKED ISSUE #184: bug: BadRequest errors received from an AttachDisk operation result in infinite retries
**What happened**:

The initial multi-az e2e test run for kubernetes-sigs/azuredisk-csi-driver#1026 failed because the uninstall of the CSI driver timed out. Looking at the logs from the run, I observed that the `attach_detach` controller was repeatedly attempting to attach at least 3 different disks to nodes in another zone. Because the attach operation was constantly retried, the `AzVolumeAttachment` instances could not be deleted resulting in a timeout while deleteing the `azure-disk-csi` namespace for the Mandalay driver.

```
E0921 01:40:06.105531       1 attach_detach.go:158] failed to attach volume pvc-e6f70d37-6089-4ca9-a498-85715f864066 to node k8s-agentpool-25396380-vmss000000: attach volume "/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-nlfju5ly/providers/Microsoft.Compute/disks/pvc-e6f70d37-6089-4ca9-a498-85715f864066" to instance "k8s-agentpool-25396380-vmss000000" failed with Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
  "error": {
    "code": "BadRequest",
    "message": "Disk /subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-nlfju5ly/providers/Microsoft.Compute/disks/pvc-e6f70d37-6089-4ca9-a498-85715f864066 cannot be attached to the VM because it is not in the same zone as the VM. VM zone: '1'. Disk zone: '2'."
  }
}
I0921 01:40:06.105596       1 util.go:51] azure_disk_utils.go:432] Initiating update with retry for *v1alpha1.AzVolumeAttachment (pvc-e6f70d37-6089-4ca9-a498-85715f864066-k8s-agentpool-25396380-vmss000000-attachment)
...
I0921 01:40:06.733478       1 request.go:600] Waited for 627.675733ms due to client-side throttling, not priority and fairness, request: PUT:https://10.0.0.1:443/apis/disk.csi.azure.com/v1alpha1/namespaces/azure-disk-csi/azvolumeattachments/pvc-e6f70d37-6089-4ca9-a498-85715f864066-k8s-agentpool-25396380-vmss000000-attachment
I0921 01:40:06.743789       1 attach_detach.go:179] Successfully updated AzVolumeAttachment (pvc-e6f70d37-6089-4ca9-a498-85715f864066-k8s-agentpool-25396380-vmss000000-attachment) with attachVolume result (response: map[], error: <nil>)
I0921 01:40:06.744845       1 util.go:51] azure_disk_utils.go:432] Initiating update with retry for *v1alpha1.AzVolumeAttachment (pvc-e6f70d37-6089-4ca9-a498-85715f864066-k8s-agentpool-25396380-vmss000000-attachment)
...
I0921 01:40:07.543253       1 attach_detach.go:139] Attaching volume (/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-nlfju5ly/providers/Microsoft.Compute/disks/pvc-e6f70d37-6089-4ca9-a498-85715f864066) to node (k8s-agentpool-25396380-vmss000000)
I0921 01:40:07.543560       1 attach_detach.go:93] Another operation (Attaching) is already in process for the AzVolumeAttachment (pvc-e6f70d37-6089-4ca9-a498-85715f864066-k8s-agentpool-25396380-vmss000000-attachment). Will be requeued once complete
```

While it is unclear how we got into this state, we shouldn't attempt to retry on a non-retriable error

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by edreed**
**What type of PR is this?**

Non-retriable errors received from cloud-provider-azure shouldn't result in retries of the same operation from the `AzVolume` and `AzVolumeAttachment`controllers. This PR centralizes conversion of errors to/from `AzError` and ensures that non-retriable from cloud-provider-azure are not retried by the controllers.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #184

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

The PR ensures that the `status.Code` set in the error generated for an `AzError` instance is `codes.FailedPrecondition` when the error is a non-retriable cloud-provider-azure error. This ensures that the [`reconcileReturnOnError`](https://github.com/abhisheksinghbaghel/azuredisk-csi-driver/blob/56f1fc62fe21295cc4e0d6b75b36ece73536c45f/pkg/controller/common.go#L630) returns `reconcile.Result{Requeue: false}`.

This PR also fixes error logging from `AttachDisk` failures and cleans up unnecessary uses of `fmt.Sprintf` with `status.Error` (instead using `status.Errorf`).

**Release note**:
```
none
```

### CODE REVIEW

File: pkg/controller/attach_detach.go [hunk 1]
```diff
@@ -152,31 +151,31 @@ func (r *ReconcileAttachDetach) triggerAttach(ctx context.Context, azVolumeAttac
...
+				_, uerr := r.updateState(ctx, azv, v1alpha1.Attached)
+				return uerr
 			}
 		}
 		if derr := azureutils.UpdateCRIWithRetry(ctx, r.client, r.azVolumeClient, azVolumeAttachment, updateFunc); derr != nil {
-			klog.Errorf("failed to update AzVolumeAttachment (%s) with attachVolume result (response: %v, error: %v): %v", azVolumeAttachment.Name, response, err, derr)
+			klog.Errorf("failed to update AzVolumeAttachment (%s) with attachVolume result (response: %v, error: %v): %v", azVolumeAttachment.Name, response, attachErr, derr)
 		} else {
-			klog.Infof("Successfully updated AzVolumeAttachment (%s) with attachVolume result (response: %v, error: %v)", azVolumeAttachment.Name, response, err)
+			klog.Infof("Successfully updated AzVolumeAttachment (%s) with attachVolume result (response: %v, error: %v)", azVolumeAttachment.Name, response, attachErr)
```
Comment (edreed) [inline pkg/controller/attach_detach.go:178]: The `attachVolume` error was being overwritten by the error returned by `r.updateState()` (OG line 163) in the error case. I renamed the `attachVolume` error and `r.updateState` error variables to improve clarity and prevent accidental overwrites in the future.

**Review by sunpa93 — APPROVED** [review]
LGTM
