### PR TITLE
test: remove redundant pre-provisioning test case

### LINKED ISSUE #167: test: no sequence that cleans up `shared-disk-multiple-pods` and `reattach-disk-multiple-nodes` volumes from e2e pre-provisioning test
**What happened**:

e2e pre-provisioning test creates volumes: `shared-disk-multiple-pods` and `reattach-disk-multiple-nodes`.

And there doesn't seem to exist a clean up sequence for these volume causing the volumes to not be deleted accordingly.

**What you expected to happen**:

All pre-provisioned volumes to be deleted after test completion.

**How to reproduce it**:

Run pre-provisioning e2e test.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by sunpa93**
…ioning test cases to ensure that the volumes get deleted after each test unless variable toggled to be true

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

- the pre-provisioning tests do not clean up created volumes.

**Which issue(s) this PR fixes**:

Fixes #167 

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

File: test/e2e/pre_provisioning_test.go [hunk 1]
```diff
@@ -43,14 +43,15 @@ var _ = ginkgo.Describe("Pre-Provisioned", func() {
 		ns         *v1.Namespace
 		testDriver driver.PreProvisionedVolumeTestDriver
 		volumeID   string
-		// Set to true if the volume should be deleted automatically after test
+		// Set to true if the volume should not be deleted automatically after test
 		skipManuallyDeletingVolume bool
```
Comment (landreasyan) [inline test/e2e/pre_provisioning_test.go:47]: Should we also rename this variable to something like ` skipVolumeDeletion` .

File: test/e2e/pre_provisioning_test.go [hunk 2]
```diff
@@ -251,7 +252,7 @@ var _ = ginkgo.Describe("Pre-Provisioned", func() {
 				ginkgo.Skip("test case is only available for in-tree driver")
 			}
 
-			skipManuallyDeletingVolume = true
+			skipVolumeDeletion = true
```
Comment (landreasyan) [inline test/e2e/pre_provisioning_test.go:255]: Do we need to skip the deletion here?

File: test/e2e/pre_provisioning_test.go [hunk 3]
```diff
@@ -450,7 +451,7 @@ var _ = ginkgo.Describe("Pre-Provisioned", func() {
 				ginkgo.Skip("test case is only available for migration test")
 			}
 
-			skipManuallyDeletingVolume = true
+			skipVolumeDeletion = true
```
Comment (landreasyan) [inline test/e2e/pre_provisioning_test.go:454]: Or here?

File: test/e2e/pre_provisioning_test.go (hunk 2 above)
Comment (sunpa93) [reply test/e2e/pre_provisioning_test.go:255]: I assumed that this was intended by the original author. Is there any reason not to delete the created volume here?

Comment (edreed) [reply test/e2e/pre_provisioning_test.go:255]: An inline volume should automatically be deleted by K8s/CSI when the pod is deleted. There shouldn't be a volume delete after the test runs.

Comment (landreasyan) [reply test/e2e/pre_provisioning_test.go:255]: Sorry for unresolving this conversation, it seems like this test is a duplicate? We have two tests that create and tests this inline volume scenario. Is that intentional?

Comment (landreasyan) [reply test/e2e/pre_provisioning_test.go:255]: https://github.com/abhisheksinghbaghel/azuredisk-csi-driver/blob/4b4960217399b8d834926cf7a824f7a9bb2447bf/test/e2e/pre_provisioning_test.go#L249
https://github.com/abhisheksinghbaghel/azuredisk-csi-driver/blob/4b4960217399b8d834926cf7a824f7a9bb2447bf/test/e2e/pre_provisioning_test.go#L249

Comment (edreed) [reply test/e2e/pre_provisioning_test.go:255]: It appears the first was added to handle testing with different schedulers. Since this test is targeting the in-tree driver, do we even need to test with the scheduler extender? It seems like we should remove this test case.

Comment (sunpa93) [reply test/e2e/pre_provisioning_test.go:255]: That sounds odd :0 And taking a quick look, the second test seems to be reserved for migration test while the first is set to be run for both.

Comment (sunpa93) [reply test/e2e/pre_provisioning_test.go:255]: And currently `pre_provisioned_inline_volume_tester` is set to take scheduler name as a param. I wonder if this should revised as well?

https://github.com/abhisheksinghbaghel/azuredisk-csi-driver/blob/4b4960217399b8d834926cf7a824f7a9bb2447bf/test/e2e/testsuites/pre_provisioned_inline_volume_tester.go#L37

**Review by landreasyan — APPROVED** [review]
